services:
  web:
    build: .
    ports:
      - "8020:8000"
    environment:
      SQLITE_PATH: /app/data/db.sqlite3
      DJANGO_ALLOWED_HOSTS: "synapse.fbstudios.com,localhost,127.0.0.1"
      DJANGO_CSRF_TRUSTED_ORIGINS: "https://synapse.fbstudios.com"
      DJANGO_DEBUG: "0"
    volumes:
      - groupf_data:/app/data

volumes:
  groupf_data:
