# Generated by Django 6.0.2 on 2026-02-19 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='base.page')),
            ],
            options={
                'unique_together': {('page', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('layout_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='base.page')),
            ],
            options={
                'unique_together': {('page', 'key')},
            },
        ),
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('landing_url', models.CharField(blank=True, max_length=800)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('viewport', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='base.page')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='base.pagevariant')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('max_scroll_pct', models.FloatField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('rollup', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='base.visitsession')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('scroll', 'Scroll'), ('view', 'View'), ('input', 'Input'), ('custom', 'Custom')], db_index=True, max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('element_key', models.CharField(blank=True, max_length=200)),
                ('css_selector', models.CharField(blank=True, max_length=500)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='base.page')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='base.visitsession')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='base.goal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='base.visitsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['page', 'started_at'], name='base_visits_page_id_94db94_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['variant', 'started_at'], name='base_visits_variant_961a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['page', 'event_type', 'occurred_at'], name='base_event_page_id_da8e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session', 'occurred_at'], name='base_event_session_31e9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['goal', 'occurred_at'], name='base_conver_goal_id_dd1512_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversion',
            unique_together={('goal', 'session')},
        ),
    ]
