# Generated by Django 6.0.2 on 2026-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='raw_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
